spring:    
 datasource:
   url: jdbc:h2:~/test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false;AUTO_SERVER=true
   driver-class-name: org.h2.Driver
   username: sa
   password: sa
 h2:
   console:
     enabled: true         
 jpa:
   properties:
     generate-ddl: true
     hibernate:
       dialect: org.hibernate.dialect.H2Dialect
       show_sql: true
       ddl-auto: create
 liquibase:
  enabled: false
  change-log: classpath:/db/changelog/changelog-master.xml
logging:
  level:
    org.springframework: ERROR
    com.mkyong: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log