
spring:    
 datasource:
   url: jdbc:h2:mem:localhost/test
   username: sa
   password: sa
 liquibase:
  change-log: classpath:/db/changelog/changelog-master.xml     
 h2:
   console:
     enabled: true         
 jpa:
   properties:
     hibernate:
       dialect: org.hibernate.dialect.H2Dialect
       show_sql: true
       ddl-auto: update       
logging:
  level:
    org.springframework: ERROR
    com.mkyong: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log  
